---
openapi: "3.0.1"
info:
  title: "Branches"
  contact: {}
  license: {}
  version: "2.0"
servers:
- url: "http://localhost:2160/brachances2/2.0"
paths:
  '{branchId}/location':
    get:
      tags: []
      summary: ""
      description: ""
      operationId: ""
      parameters: []
      responses:
        200:
          description: "sample response"
          content:
            text/plain: {}
      security: []
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  extensions: {}
